FROM node:18 AS build
WORKDIR /app

COPY package*.json ./
RUN npm install


COPY .env .env

COPY . .
RUN npm run build

# Etapa 2: Nginx
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]



