version: '3.8'

services:
  backend:
    image: jozneto/svault-backend:latest
    ports:
      - "8000:8000"
    environment:
      - APP_SECRET_KEY=${APP_SECRET_KEY}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASS=${MONGODB_PASS}
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_URI=mongodb+srv://${MONGODB_USER}:${MONGODB_PASS}@${MONGODB_HOST}

  frontend:
    image: jozneto/svault-frontend:latest
    ports:
      - "3000:3000"

    environment:
      - REACT_APP_API_URL=http://backend:8000
    depends_on:
      - backend
